Add Alfen Evcs
opernikus-common/openems pull request #29
Opened 2023-11-14 12:36 UTC by TimStoecker

*Add Alfen Evcs Based on PR#28

2023-11-14 13:39 UTC, yvesilknievil commented
Hi @TimStoecker 

Thanks for acting so quick on this topic.
I merged it to my fork, and do notice some strange behaviour:
When I start charging, it starts and then after a while the controller says: battery full and the charging stops.
The cycle then repeats itself.

Anything I would've missed?

2023-11-14 15:23 UTC, TimStoecker commented
Hi @yvesilknievil 

Thank you for testing of the Alfen Implementation. I checked again and the translation of the Status is not well explained in the documentation. It is possible that the previous mapping of the register was wrong. I changed it to the one of the IEC62196 specification.
Let me know if the error persists!

2023-11-15 13:01 UTC, clehne requested changes

2023-11-15 13:01 UTC, clehne commented on io.openems.edge.evcs.alfen/src/io/openems/edge/evcs/alfen/EvcsAlfen.java
> +		APPARENT_POWER_L1(Doc.of(OpenemsType.FLOAT).unit(Unit.VOLT_AMPERE) //
We should remove apparentPowerL1,2,3, reactivePowerL1,2,3, energy deliveredL1,2,3/consumedL1,2,3. They are unnessesary for all usecases I can think off.

2023-11-15 13:03 UTC, clehne commented
Like that bundle. Please remove the unnessesary channels and rebase (due to merged #28).

2023-11-22 09:08 UTC, clehne approved these changes
Great.

2023-11-22 09:08 UTC, merged