Move Timer natures from edge.core to edge.common
opernikus-common/openems pull request #54
Opened 2024-02-19 17:30 UTC by clehne

Removed edge.core dependancy in evcs.cluster.chargemanagement

2024-02-20 08:38 UTC, tsicking requested changes
Additionally, we should remove `io.openems.edge.core` from the buildpath of `io.openems.edge.evcs.compleo` and `io.openems.edge.controller.evcs.vehiclebatterysymmetric`.

2024-02-20 08:38 UTC, tsicking commented on io.openems.edge.common/test/io/openems/edge/common/statemachine/StateMachineTest.java
This shouldn't be part of this PR, should it?

2024-02-20 08:38 UTC, tsicking commented on io.openems.edge.common/test/io/openems/edge/common/statemachine/StateMachineTest.java
Oh, I see, it may be just sorting of imports due to `prepare-commit.sh`. Let's leave it here then.

2024-02-20 08:38 UTC, tsicking commented on io.openems.edge.core/test/io/openems/edge/core/appmanager/Apps.java
Same as for `StateMachineTest.java`.

2024-02-20 08:38 UTC, tsicking commented on io.openems.edge.core/test/io/openems/edge/core/timer/MyConfig.java
>  }
Should we have a CRLF here?

2024-02-20 10:21 UTC, tsicking approved these changes
Should be okay now.

2024-02-23 18:08 UTC, clehne reviewed
Changes looks good. @tsicking Thanks for fixing it.

2024-02-23 18:08 UTC, merged