More descriptive explanation of the EVCS Cluster Chargemanamgenent
opernikus-common/openems pull request #55
Opened 2024-02-19 17:33 UTC by clehne

More descriptive explanation of the EVCS Cluster Chargemanamgenent

2024-02-21 09:20 UTC, tsicking requested changes
See my comments, mostly small typos.

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +of 15min, it is <= `targetPower`.
The `<=` is converted to an arrow, so this doesn't look nice. Maybe better:
"It may be exceeded for a few seconds, but over a period of 15 minutes, the power of the cluster will be less or equal to `targetPower` on average." Or something similar...

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +An industrial property may have a grid connection with 150A fuse. Within the customers property a 100kWp PV is installed.
"with **a** 150A fuse."

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +The Evcs Cluster Chargemanagment will now limit the chargepoint either to the more critical limit on the grid or to the more critical limit on the parking lot.
This sounds a bit complicated. Maybe:
"The Evcs Cluster Chargemanagement will take care that neither of the limits is exceeded."

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +The Evcs Cluster Chargemanagement provides three states:
"has three states"? "can be in three states"? "provides" doesn't sound right here to me.

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +* State `RED` - all chargepoints are switched to off. This state is reached when
"all chargepoints are switched off."

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +* State `YELLOW` - charge management is done by a round robin algorithm. This state is reached, when the minimum power of all charge points, that want to
"on all charge points that want to charge" without the ",". I would also leave the other "," before "when" out.

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +charge exceeds the configured `targetPower`. In that case one or more charge points are switched off. And the others will be activated/switched off
I don't understand what that means. One or more chargepoints are switched off and the others will be operated by a round robin algorithm? I thought all are operated by a round robin algorithm.

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +* State `GREEN` - all requested charge points are allowed to charge. They will be operated in between min and max power. The management is done by leveling.
Maybe better: "They will be operated in between min and max power so that `targetPower` is not exceeded.

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +* `MeterEvcsClusterCmVirtual` - virtual meter which can be put in front of a ecvs cluster chargemanagement. It provides an `ElectricityMeter` for the cluster. this meter
"in front of **an evcs** cluster chargemanagement. [...] **T**his meter can be used by a cluster limiter for the same cluster" sounds a bit less complicated.

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +than can be used by a cluster limiter which can be given to the same cluster. With this meter a cluster can be limited on its own. OSGI-Circular dependency is avoided by the way
OSG**i**

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +* to avoid continuously incrementation/decrementation around the `targetpower` limit a "TargetPowerZone" is introduced. When the cluster is operated within the
**T**o avoid...

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +* junit test does not work right now.
**JU**nit test

2024-02-21 09:20 UTC, tsicking commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
In ## Configuration:
`evcs_ids` and `evcsClusterLimiter_ids`.
I would also say in `evcs_ids`: "IDs of the evcss to control", as you are not controlling the ids :-)

Also: Should we explain how to configure a limiter, or is that self explanatory?

2024-02-27 18:21 UTC, clehne commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +of 15min, it is <= `targetPower`.
Done

2024-02-27 18:22 UTC, clehne commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +The Evcs Cluster Chargemanagment will now limit the chargepoint either to the more critical limit on the grid or to the more critical limit on the parking lot.
Replaced

2024-02-27 18:27 UTC, clehne commented on io.openems.edge.evcs.cluster.chargemanagement/readme.adoc
> +charge exceeds the configured `targetPower`. In that case one or more charge points are switched off. And the others will be activated/switched off
Explained more clear

2024-02-27 18:44 UTC, clehne commented
Added review requests from @tsicking

2024-02-28 08:24 UTC, tsicking approved these changes

2024-02-28 08:49 UTC, merged